### ISSUE TITLE
In 1.15.2 the y and z value is a bit off

### ISSUE THREAD

**Issue by imt314** [Fallen-Breath/PearlCannonHelper#1]
![ingame](https://user-images.githubusercontent.com/36664975/80284350-5bf87680-871e-11ea-817d-49be9c85df9f.png)
![PearlCannonHelper](https://user-images.githubusercontent.com/36664975/80284354-61ee5780-871e-11ea-899d-cd8fa18c512d.PNG)

**Comment by Fallen-Breath** [comment]
u're using the default 360ftlh infomation and the 360ftlh wdl right? what's the bit sequence u used? and ofc make sure you have entered the same config as the 360ftlh in game

**Comment by imt314** [comment]
i tested again with the programs from the wdl and even those are off by a bit

**Comment by imt314** [comment]
seems like something tnt / alignment related changed in 1.15.2

**Comment by Fallen-Breath** [comment]
what's the bit sequence u used? there's nothing changed in 1.15.2 and i'm sure it works. the cannon itself even works well in lastest snapshot 20w17a
make sure your client is vanilla enough

**Comment by imt314** [comment]
I used this bit sequence : [110 001] [0100 0001] [1 01010 00 10111] and tested on a carpet server

**Comment by Fallen-Breath** [comment]
are u using the latestest wdl? the first release wdl i made has a issue about programming the cannon, there are 2 10tnt modules that cannot be controlled. that might be the issue

i have tested that bit sequence in 1.15.2 it works fine (at least in the first 2 gt but that's enough)

**Comment by imt314** [comment]
yes i used the latest wdl

**Comment by imt314** [comment]
but even the pre-programed location from the wdl aren't 100% accurate

**Comment by Fallen-Breath** [comment]
the pre-programed locations are fine in my test tho

**Comment by Fallen-Breath** [comment]
the top decode for diorite is a little broken in 1.15 because the comparator as below won't light up. idk what mojang has changed
![image](https://user-images.githubusercontent.com/28978806/81034641-6c50e400-8eca-11ea-9ac9-c803511562ea.png)

**Comment by Fallen-Breath** [comment]
check this https://youtu.be/8cZyuu7nPXY

**Comment by imt314** [comment]
ok thanks :)
